

# Opencart countries
# {"name": "Aaland Islands", "iso_code_2": "AX", "iso_code_3": "ALA"},
# {"name": "Afghanistan", "iso_code_2": "AF", "iso_code_3": "AFG"},
# {"name": "Albania", "iso_code_2": "AL", "iso_code_3": "ALB"},
# {"name": "Algeria", "iso_code_2": "DZ", "iso_code_3": "DZA"},
# {"name": "American Samoa", "iso_code_2": "AS", "iso_code_3": "ASM"},
# {"name": "Andorra", "iso_code_2": "AD", "iso_code_3": "AND"},
# {"name": "Angola", "iso_code_2": "AO", "iso_code_3": "AGO"},
# {"name": "Anguilla", "iso_code_2": "AI", "iso_code_3": "AIA"},
# {"name": "Antarctica", "iso_code_2": "AQ", "iso_code_3": "ATA"},
# {"name": "Antigua and Barbuda", "iso_code_2": "AG", "iso_code_3": "ATG"},
# {"name": "Argentina", "iso_code_2": "AR", "iso_code_3": "ARG"},
# {"name": "Armenia", "iso_code_2": "AM", "iso_code_3": "ARM"},
# {"name": "Aruba", "iso_code_2": "AW", "iso_code_3": "ABW"},
# {"name": "Ascension Island (British)", "iso_code_2": "AC", "iso_code_3": "ASC"},
# {"name": "Australia", "iso_code_2": "AU", "iso_code_3": "AUS"},
# {"name": "Austria", "iso_code_2": "AT", "iso_code_3": "AUT"},
# {"name": "Azerbaijan", "iso_code_2": "AZ", "iso_code_3": "AZE"},
# {"name": "Bahamas", "iso_code_2": "BS", "iso_code_3": "BHS"},
# {"name": "Bahrain", "iso_code_2": "BH", "iso_code_3": "BHR"},
# {"name": "Bangladesh", "iso_code_2": "BD", "iso_code_3": "BGD"},
# {"name": "Barbados", "iso_code_2": "BB", "iso_code_3": "BRB"},
# {"name": "Belarus", "iso_code_2": "BY", "iso_code_3": "BLR"},
# {"name": "Belgium", "iso_code_2": "BE", "iso_code_3": "BEL"},
# {"name": "Belize", "iso_code_2": "BZ", "iso_code_3": "BLZ"},
# {"name": "Benin", "iso_code_2": "BJ", "iso_code_3": "BEN"},
# {"name": "Bermuda", "iso_code_2": "BM", "iso_code_3": "BMU"},
# {"name": "Bhutan", "iso_code_2": "BT", "iso_code_3": "BTN"},
# {"name": "Bolivia", "iso_code_2": "BO", "iso_code_3": "BOL"},
# {"name": "Bonaire, Sint Eustatius and Saba", "iso_code_2": "BQ", "iso_code_3": "BES"},
# {"name": "Bosnia and Herzegovina", "iso_code_2": "BA", "iso_code_3": "BIH"},
# {"name": "Botswana", "iso_code_2": "BW", "iso_code_3": "BWA"},
# {"name": "Bouvet Island", "iso_code_2": "BV", "iso_code_3": "BVT"},
# {"name": "Brazil", "iso_code_2": "BR", "iso_code_3": "BRA"},
# {"name": "British Indian Ocean Territory", "iso_code_2": "IO", "iso_code_3": "IOT"},
# {"name": "Brunei Darussalam", "iso_code_2": "BN", "iso_code_3": "BRN"},
# {"name": "Bulgaria", "iso_code_2": "BG", "iso_code_3": "BGR"},
# {"name": "Burkina Faso", "iso_code_2": "BF", "iso_code_3": "BFA"},
# {"name": "Burundi", "iso_code_2": "BI", "iso_code_3": "BDI"},
# {"name": "Cambodia", "iso_code_2": "KH", "iso_code_3": "KHM"},
# {"name": "Cameroon", "iso_code_2": "CM", "iso_code_3": "CMR"},
# {"name": "Canada", "iso_code_2": "CA", "iso_code_3": "CAN"},
# {"name": "Canary Islands", "iso_code_2": "IC", "iso_code_3": "ICA"},
# {"name": "Cape Verde", "iso_code_2": "CV", "iso_code_3": "CPV"},
# {"name": "Cayman Islands", "iso_code_2": "KY", "iso_code_3": "CYM"},
# {"name": "Central African Republic", "iso_code_2": "CF", "iso_code_3": "CAF"},
# {"name": "Chad", "iso_code_2": "TD", "iso_code_3": "TCD"},
# {"name": "Chile", "iso_code_2": "CL", "iso_code_3": "CHL"},
# {"name": "China", "iso_code_2": "CN", "iso_code_3": "CHN"},
# {"name": "Christmas Island", "iso_code_2": "CX", "iso_code_3": "CXR"},
# {"name": "Cocos (Keeling) Islands", "iso_code_2": "CC", "iso_code_3": "CCK"},
# {"name": "Colombia", "iso_code_2": "CO", "iso_code_3": "COL"},
# {"name": "Comoros", "iso_code_2": "KM", "iso_code_3": "COM"},
# {"name": "Congo", "iso_code_2": "CG", "iso_code_3": "COG"},
# {"name": "Cook Islands", "iso_code_2": "CK", "iso_code_3": "COK"},
# {"name": "Costa Rica", "iso_code_2": "CR", "iso_code_3": "CRI"},
# {"name": "Cote D'Ivoire", "iso_code_2": "CI", "iso_code_3": "CIV"},
# {"name": "Croatia", "iso_code_2": "HR", "iso_code_3": "HRV"},
# {"name": "Cuba", "iso_code_2": "CU", "iso_code_3": "CUB"},
# {"name": "Curacao", "iso_code_2": "CW", "iso_code_3": "CUW"},
# {"name": "Cyprus", "iso_code_2": "CY", "iso_code_3": "CYP"},
# {"name": "Czech Republic", "iso_code_2": "CZ", "iso_code_3": "CZE"},
# {"name": "Democratic Republic of Congo", "iso_code_2": "CD", "iso_code_3": "COD"},
# {"name": "Denmark", "iso_code_2": "DK", "iso_code_3": "DNK"},
# {"name": "Djibouti", "iso_code_2": "DJ", "iso_code_3": "DJI"},
# {"name": "Dominica", "iso_code_2": "DM", "iso_code_3": "DMA"},
# {"name": "Dominican Republic", "iso_code_2": "DO", "iso_code_3": "DOM"},
# {"name": "East Timor", "iso_code_2": "TL", "iso_code_3": "TLS"},
# {"name": "Ecuador", "iso_code_2": "EC", "iso_code_3": "ECU"},
# {"name": "Egypt", "iso_code_2": "EG", "iso_code_3": "EGY"},
# {"name": "El Salvador", "iso_code_2": "SV", "iso_code_3": "SLV"},
# {"name": "Equatorial Guinea", "iso_code_2": "GQ", "iso_code_3": "GNQ"},
# {"name": "Eritrea", "iso_code_2": "ER", "iso_code_3": "ERI"},
# {"name": "Estonia", "iso_code_2": "EE", "iso_code_3": "EST"},
# {"name": "Ethiopia", "iso_code_2": "ET", "iso_code_3": "ETH"},
# {"name": "Falkland Islands (Malvinas)", "iso_code_2": "FK", "iso_code_3": "FLK"},
# {"name": "Faroe Islands", "iso_code_2": "FO", "iso_code_3": "FRO"},
# {"name": "Fiji", "iso_code_2": "FJ", "iso_code_3": "FJI"},
# {"name": "Finland", "iso_code_2": "FI", "iso_code_3": "FIN"},
# {"name": "France, Metropolitan", "iso_code_2": "FR", "iso_code_3": "FRA"},
# {"name": "French Guiana", "iso_code_2": "GF", "iso_code_3": "GUF"},
# {"name": "French Polynesia", "iso_code_2": "PF", "iso_code_3": "PYF"},
# {"name": "French Southern Territories", "iso_code_2": "TF", "iso_code_3": "ATF"},
# {"name": "FYROM", "iso_code_2": "MK", "iso_code_3": "MKD"},
# {"name": "Gabon", "iso_code_2": "GA", "iso_code_3": "GAB"},
# {"name": "Gambia", "iso_code_2": "GM", "iso_code_3": "GMB"},
# {"name": "Georgia", "iso_code_2": "GE", "iso_code_3": "GEO"},
# {"name": "Germany", "iso_code_2": "DE", "iso_code_3": "DEU"},
# {"name": "Ghana", "iso_code_2": "GH", "iso_code_3": "GHA"},
# {"name": "Gibraltar", "iso_code_2": "GI", "iso_code_3": "GIB"},
# {"name": "Greece", "iso_code_2": "GR", "iso_code_3": "GRC"},
# {"name": "Greenland", "iso_code_2": "GL", "iso_code_3": "GRL"},
# {"name": "Grenada", "iso_code_2": "GD", "iso_code_3": "GRD"},
# {"name": "Guadeloupe", "iso_code_2": "GP", "iso_code_3": "GLP"},
# {"name": "Guam", "iso_code_2": "GU", "iso_code_3": "GUM"},
# {"name": "Guatemala", "iso_code_2": "GT", "iso_code_3": "GTM"},
# {"name": "Guernsey", "iso_code_2": "GG", "iso_code_3": "GGY"},
# {"name": "Guinea", "iso_code_2": "GN", "iso_code_3": "GIN"},
# {"name": "Guinea-Bissau", "iso_code_2": "GW", "iso_code_3": "GNB"},
# {"name": "Guyana", "iso_code_2": "GY", "iso_code_3": "GUY"},
# {"name": "Haiti", "iso_code_2": "HT", "iso_code_3": "HTI"},
# {"name": "Heard and Mc Donald Islands", "iso_code_2": "HM", "iso_code_3": "HMD"},
# {"name": "Honduras", "iso_code_2": "HN", "iso_code_3": "HND"},
# {"name": "Hong Kong", "iso_code_2": "HK", "iso_code_3": "HKG"},
# {"name": "Hungary", "iso_code_2": "HU", "iso_code_3": "HUN"},
# {"name": "Iceland", "iso_code_2": "IS", "iso_code_3": "ISL"},
# {"name": "India", "iso_code_2": "IN", "iso_code_3": "IND"},
# {"name": "Indonesia", "iso_code_2": "ID", "iso_code_3": "IDN"},
# {"name": "Iran (Islamic Republic of)", "iso_code_2": "IR", "iso_code_3": "IRN"},
# {"name": "Iraq", "iso_code_2": "IQ", "iso_code_3": "IRQ"},
# {"name": "Ireland", "iso_code_2": "IE", "iso_code_3": "IRL"},
# {"name": "Isle of Man", "iso_code_2": "IM", "iso_code_3": "IMN"},
# {"name": "Israel", "iso_code_2": "IL", "iso_code_3": "ISR"},
# {"name": "Italy", "iso_code_2": "IT", "iso_code_3": "ITA"},
# {"name": "Jamaica", "iso_code_2": "JM", "iso_code_3": "JAM"},
# {"name": "Japan", "iso_code_2": "JP", "iso_code_3": "JPN"},
# {"name": "Jersey", "iso_code_2": "JE", "iso_code_3": "JEY"},
# {"name": "Jordan", "iso_code_2": "JO", "iso_code_3": "JOR"},
# {"name": "Kazakhstan", "iso_code_2": "KZ", "iso_code_3": "KAZ"},
# {"name": "Kenya", "iso_code_2": "KE", "iso_code_3": "KEN"},
# {"name": "Kiribati", "iso_code_2": "KI", "iso_code_3": "KIR"},
# {"name": "Korea, Republic of", "iso_code_2": "KR", "iso_code_3": "KOR"},
# {"name": "Kosovo, Republic of", "iso_code_2": "XK", "iso_code_3": "UNK"},
# {"name": "Kuwait", "iso_code_2": "KW", "iso_code_3": "KWT"},
# {"name": "Kyrgyzstan", "iso_code_2": "KG", "iso_code_3": "KGZ"},
# {"name": "Lao People's Democratic Republic", "iso_code_2": "LA", "iso_code_3": "LAO"},
# {"name": "Latvia", "iso_code_2": "LV", "iso_code_3": "LVA"},
# {"name": "Lebanon", "iso_code_2": "LB", "iso_code_3": "LBN"},
# {"name": "Lesotho", "iso_code_2": "LS", "iso_code_3": "LSO"},
# {"name": "Liberia", "iso_code_2": "LR", "iso_code_3": "LBR"},
# {"name": "Libyan Arab Jamahiriya", "iso_code_2": "LY", "iso_code_3": "LBY"},
# {"name": "Liechtenstein", "iso_code_2": "LI", "iso_code_3": "LIE"},
# {"name": "Lithuania", "iso_code_2": "LT", "iso_code_3": "LTU"},
# {"name": "Luxembourg", "iso_code_2": "LU", "iso_code_3": "LUX"},
# {"name": "Macau", "iso_code_2": "MO", "iso_code_3": "MAC"},
# {"name": "Madagascar", "iso_code_2": "MG", "iso_code_3": "MDG"},
# {"name": "Malawi", "iso_code_2": "MW", "iso_code_3": "MWI"},
# {"name": "Malaysia", "iso_code_2": "MY", "iso_code_3": "MYS"},
# {"name": "Maldives", "iso_code_2": "MV", "iso_code_3": "MDV"},
# {"name": "Mali", "iso_code_2": "ML", "iso_code_3": "MLI"},
# {"name": "Malta", "iso_code_2": "MT", "iso_code_3": "MLT"},
# {"name": "Marshall Islands", "iso_code_2": "MH", "iso_code_3": "MHL"},
# {"name": "Martinique", "iso_code_2": "MQ", "iso_code_3": "MTQ"},
# {"name": "Mauritania", "iso_code_2": "MR", "iso_code_3": "MRT"},
# {"name": "Mauritius", "iso_code_2": "MU", "iso_code_3": "MUS"},
# {"name": "Mayotte", "iso_code_2": "YT", "iso_code_3": "MYT"},
# {"name": "Mexico", "iso_code_2": "MX", "iso_code_3": "MEX"},
# {"name": "Micronesia, Federated States of", "iso_code_2": "FM", "iso_code_3": "FSM"},
# {"name": "Moldova, Republic of", "iso_code_2": "MD", "iso_code_3": "MDA"},
# {"name": "Monaco", "iso_code_2": "MC", "iso_code_3": "MCO"},
# {"name": "Mongolia", "iso_code_2": "MN", "iso_code_3": "MNG"},
# {"name": "Montenegro", "iso_code_2": "ME", "iso_code_3": "MNE"},
# {"name": "Montserrat", "iso_code_2": "MS", "iso_code_3": "MSR"},
# {"name": "Morocco", "iso_code_2": "MA", "iso_code_3": "MAR"},
# {"name": "Mozambique", "iso_code_2": "MZ", "iso_code_3": "MOZ"},
# {"name": "Myanmar", "iso_code_2": "MM", "iso_code_3": "MMR"},
# {"name": "Namibia", "iso_code_2": "NA", "iso_code_3": "NAM"},
# {"name": "Nauru", "iso_code_2": "NR", "iso_code_3": "NRU"},
# {"name": "Nepal", "iso_code_2": "NP", "iso_code_3": "NPL"},
# {"name": "Netherlands", "iso_code_2": "NL", "iso_code_3": "NLD"},
# {"name": "Netherlands Antilles", "iso_code_2": "AN", "iso_code_3": "ANT"},
# {"name": "New Caledonia", "iso_code_2": "NC", "iso_code_3": "NCL"},
# {"name": "New Zealand", "iso_code_2": "NZ", "iso_code_3": "NZL"},
# {"name": "Nicaragua", "iso_code_2": "NI", "iso_code_3": "NIC"},
# {"name": "Niger", "iso_code_2": "NE", "iso_code_3": "NER"},
# {"name": "Nigeria", "iso_code_2": "NG", "iso_code_3": "NGA"},
# {"name": "Niue", "iso_code_2": "NU", "iso_code_3": "NIU"},
# {"name": "Norfolk Island", "iso_code_2": "NF", "iso_code_3": "NFK"},
# {"name": "North Korea", "iso_code_2": "KP", "iso_code_3": "PRK"},
# {"name": "Northern Mariana Islands", "iso_code_2": "MP", "iso_code_3": "MNP"},
# {"name": "Norway", "iso_code_2": "NO", "iso_code_3": "NOR"},
# {"name": "Oman", "iso_code_2": "OM", "iso_code_3": "OMN"},
# {"name": "Pakistan", "iso_code_2": "PK", "iso_code_3": "PAK"},
# {"name": "Palau", "iso_code_2": "PW", "iso_code_3": "PLW"},
# {"name": "Palestinian Territory, Occupied", "iso_code_2": "PS", "iso_code_3": "PSE"},
# {"name": "Panama", "iso_code_2": "PA", "iso_code_3": "PAN"},
# {"name": "Papua New Guinea", "iso_code_2": "PG", "iso_code_3": "PNG"},
# {"name": "Paraguay", "iso_code_2": "PY", "iso_code_3": "PRY"},
# {"name": "Peru", "iso_code_2": "PE", "iso_code_3": "PER"},
# {"name": "Philippines", "iso_code_2": "PH", "iso_code_3": "PHL"},
# {"name": "Pitcairn", "iso_code_2": "PN", "iso_code_3": "PCN"},
# {"name": "Poland", "iso_code_2": "PL", "iso_code_3": "POL"},
# {"name": "Portugal", "iso_code_2": "PT", "iso_code_3": "PRT"},
# {"name": "Puerto Rico", "iso_code_2": "PR", "iso_code_3": "PRI"},
# {"name": "Qatar", "iso_code_2": "QA", "iso_code_3": "QAT"},
# {"name": "Reunion", "iso_code_2": "RE", "iso_code_3": "REU"},
# {"name": "Romania", "iso_code_2": "RO", "iso_code_3": "ROM"},
# {"name": "Russian Federation", "iso_code_2": "RU", "iso_code_3": "RUS"},
# {"name": "Rwanda", "iso_code_2": "RW", "iso_code_3": "RWA"},
# {"name": "Saint Kitts and Nevis", "iso_code_2": "KN", "iso_code_3": "KNA"},
# {"name": "Saint Lucia", "iso_code_2": "LC", "iso_code_3": "LCA"},
# {"name": "Saint Vincent and the Grenadines", "iso_code_2": "VC", "iso_code_3": "VCT"},
# {"name": "Samoa", "iso_code_2": "WS", "iso_code_3": "WSM"},
# {"name": "San Marino", "iso_code_2": "SM", "iso_code_3": "SMR"},
# {"name": "Sao Tome and Principe", "iso_code_2": "ST", "iso_code_3": "STP"},
# {"name": "Saudi Arabia", "iso_code_2": "SA", "iso_code_3": "SAU"},
# {"name": "Senegal", "iso_code_2": "SN", "iso_code_3": "SEN"},
# {"name": "Serbia", "iso_code_2": "RS", "iso_code_3": "SRB"},
# {"name": "Seychelles", "iso_code_2": "SC", "iso_code_3": "SYC"},
# {"name": "Sierra Leone", "iso_code_2": "SL", "iso_code_3": "SLE"},
# {"name": "Singapore", "iso_code_2": "SG", "iso_code_3": "SGP"},
# {"name": "Slovak Republic", "iso_code_2": "SK", "iso_code_3": "SVK"},
# {"name": "Slovenia", "iso_code_2": "SI", "iso_code_3": "SVN"},
# {"name": "Solomon Islands", "iso_code_2": "SB", "iso_code_3": "SLB"},
# {"name": "Somalia", "iso_code_2": "SO", "iso_code_3": "SOM"},
# {"name": "South Africa", "iso_code_2": "ZA", "iso_code_3": "ZAF"},
# {"name": "South Georgia &amp; South Sandwich Islands", "iso_code_2": "GS", "iso_code_3": "SGS"},
# {"name": "South Sudan", "iso_code_2": "SS", "iso_code_3": "SSD"},
# {"name": "Spain", "iso_code_2": "ES", "iso_code_3": "ESP"},
# {"name": "Sri Lanka", "iso_code_2": "LK", "iso_code_3": "LKA"},
# {"name": "St. Barthelemy", "iso_code_2": "BL", "iso_code_3": "BLM"},
# {"name": "St. Helena", "iso_code_2": "SH", "iso_code_3": "SHN"},
# {"name": "St. Martin (French part)", "iso_code_2": "MF", "iso_code_3": "MAF"},
# {"name": "St. Pierre and Miquelon", "iso_code_2": "PM", "iso_code_3": "SPM"},
# {"name": "Sudan", "iso_code_2": "SD", "iso_code_3": "SDN"},
# {"name": "Suriname", "iso_code_2": "SR", "iso_code_3": "SUR"},
# {"name": "Svalbard and Jan Mayen Islands", "iso_code_2": "SJ", "iso_code_3": "SJM"},
# {"name": "Swaziland", "iso_code_2": "SZ", "iso_code_3": "SWZ"},
# {"name": "Sweden", "iso_code_2": "SE", "iso_code_3": "SWE"},
# {"name": "Switzerland", "iso_code_2": "CH", "iso_code_3": "CHE"},
# {"name": "Syrian Arab Republic", "iso_code_2": "SY", "iso_code_3": "SYR"},
# {"name": "Taiwan", "iso_code_2": "TW", "iso_code_3": "TWN"},
# {"name": "Tajikistan", "iso_code_2": "TJ", "iso_code_3": "TJK"},
# {"name": "Tanzania, United Republic of", "iso_code_2": "TZ", "iso_code_3": "TZA"},
# {"name": "Thailand", "iso_code_2": "TH", "iso_code_3": "THA"},
# {"name": "Togo", "iso_code_2": "TG", "iso_code_3": "TGO"},
# {"name": "Tokelau", "iso_code_2": "TK", "iso_code_3": "TKL"},
# {"name": "Tonga", "iso_code_2": "TO", "iso_code_3": "TON"},
# {"name": "Trinidad and Tobago", "iso_code_2": "TT", "iso_code_3": "TTO"},
# {"name": "Tristan da Cunha", "iso_code_2": "TA", "iso_code_3": "SHN"},
# {"name": "Tunisia", "iso_code_2": "TN", "iso_code_3": "TUN"},
# {"name": "Turkey", "iso_code_2": "TR", "iso_code_3": "TUR"},
# {"name": "Turkmenistan", "iso_code_2": "TM", "iso_code_3": "TKM"},
# {"name": "Turks and Caicos Islands", "iso_code_2": "TC", "iso_code_3": "TCA"},
# {"name": "Tuvalu", "iso_code_2": "TV", "iso_code_3": "TUV"},
# {"name": "Uganda", "iso_code_2": "UG", "iso_code_3": "UGA"},
# {"name": "Ukraine", "iso_code_2": "UA", "iso_code_3": "UKR"},
# {"name": "United Arab Emirates", "iso_code_2": "AE", "iso_code_3": "ARE"},
# {"name": "United Kingdom", "iso_code_2": "GB", "iso_code_3": "GBR"},
# {"name": "United States", "iso_code_2": "US", "iso_code_3": "USA"},
# {"name": "United States Minor Outlying Islands", "iso_code_2": "UM", "iso_code_3": "UMI"},
# {"name": "Uruguay", "iso_code_2": "UY", "iso_code_3": "URY"},
# {"name": "Uzbekistan", "iso_code_2": "UZ", "iso_code_3": "UZB"},
# {"name": "Vanuatu", "iso_code_2": "VU", "iso_code_3": "VUT"},
# {"name": "Vatican City State (Holy See)", "iso_code_2": "VA", "iso_code_3": "VAT"},
# {"name": "Venezuela", "iso_code_2": "VE", "iso_code_3": "VEN"},
# {"name": "Viet Nam", "iso_code_2": "VN", "iso_code_3": "VNM"},
# {"name": "Virgin Islands (British)", "iso_code_2": "VG", "iso_code_3": "VGB"},
# {"name": "Virgin Islands (U.S.)", "iso_code_2": "VI", "iso_code_3": "VIR"},
# {"name": "Wallis and Futuna Islands", "iso_code_2": "WF", "iso_code_3": "WLF"},
# {"name": "Western Sahara", "iso_code_2": "EH", "iso_code_3": "ESH"},
# {"name": "Yemen", "iso_code_2": "YE", "iso_code_3": "YEM"},
# {"name": "Zambia", "iso_code_2": "ZM", "iso_code_3": "ZMB"},
# {"name": "Zimbabwe", "iso_code_2": "ZW", "iso_code_3": "ZWE"}


DEFAULT = "All Territories"

ISO_CODE3_TO_TERRITORY_MAP = {
    "CAN": {"name": "Canada", "zones": {
        "AB": {"name": "Alberta"},
        "BC": {"name": "British Columbia"},
        "MB": {"name": "Manitoba"},
        "NB": {"name": "New Brunswick"},
        "NL": {"name": "Newfoundland and Labrador"},
        "NT": {"name": "Northwest Territories"},
        "NS": {"name": "Nova Scotia"},
        "NU": {"name": "Nunavut"},
        "ON": {"name": "Ontario"},
        "PE": {"name": "Prince Edward Island"},
        "QC": {"name": "Quebec"},
        "SK": {"name": "Saskatchewan"},
        "YT": {"name": "Yukon Territory"}
    }},
    "ALA": {"name": "Aaland Islands"},
    "AFG": {"name": "Afghanistan"},
    "ALB": {"name": "Albania"},
    "DZA": {"name": "Algeria"},
    "ASM": {"name": "American Samoa"},
    "AND": {"name": "Andorra"},
    "AGO": {"name": "Angola"},
    "AIA": {"name": "Anguilla"},
    "ATA": {"name": "Antarctica"},
    "ATG": {"name": "Antigua and Barbuda"},
    "ARG": {"name": "Argentina"},
    "ARM": {"name": "Armenia"},
    "ABW": {"name": "Aruba"},
    "ASC": {"name": "Ascension Island (British)"},
    "AUS": {"name": "Australia"},
    "AUT": {"name": "Austria"},
    "AZE": {"name": "Azerbaijan"},
    "BHS": {"name": "Bahamas"},
    "BHR": {"name": "Bahrain"},
    "BGD": {"name": "Bangladesh"},
    "BRB": {"name": "Barbados"},
    "BLR": {"name": "Belarus"},
    "BEL": {"name": "Belgium"},
    "BLZ": {"name": "Belize"},
    "BEN": {"name": "Benin"},
    "BMU": {"name": "Bermuda"},
    "BTN": {"name": "Bhutan"},
    "BOL": {"name": "Bolivia"},
    "BES": {"name": "Bonaire, Sint Eustatius and Saba"},
    "BIH": {"name": "Bosnia and Herzegovina"},
    "BWA": {"name": "Botswana"},
    "BVT": {"name": "Bouvet Island"},
    "BRA": {"name": "Brazil"},
    "IOT": {"name": "British Indian Ocean Territory"},
    "BRN": {"name": "Brunei Darussalam"},
    "BGR": {"name": "Bulgaria"},
    "BFA": {"name": "Burkina Faso"},
    "BDI": {"name": "Burundi"},
    "KHM": {"name": "Cambodia"},
    "CMR": {"name": "Cameroon"},
    "ICA": {"name": "Canary Islands"},
    "CPV": {"name": "Cape Verde"},
    "CYM": {"name": "Cayman Islands"},
    "CAF": {"name": "Central African Republic"},
    "TCD": {"name": "Chad"},
    "CHL": {"name": "Chile"},
    "CHN": {"name": "China"},
    "CXR": {"name": "Christmas Island"},
    "CCK": {"name": "Cocos (Keeling) Islands"},
    "COL": {"name": "Colombia"},
    "COM": {"name": "Comoros"},
    "COG": {"name": "Congo"},
    "COK": {"name": "Cook Islands"},
    "CRI": {"name": "Costa Rica"},
    "CIV": {"name": "Cote D'Ivoire"},
    "HRV": {"name": "Croatia"},
    "CUB": {"name": "Cuba"},
    "CUW": {"name": "Curacao"},
    "CYP": {"name": "Cyprus"},
    "CZE": {"name": "Czech Republic"},
    "COD": {"name": "Democratic Republic of Congo"},
    "DNK": {"name": "Denmark"},
    "DJI": {"name": "Djibouti"},
    "DMA": {"name": "Dominica"},
    "DOM": {"name": "Dominican Republic"},
    "TLS": {"name": "East Timor"},
    "ECU": {"name": "Ecuador"},
    "EGY": {"name": "Egypt"},
    "SLV": {"name": "El Salvador"},
    "GNQ": {"name": "Equatorial Guinea"},
    "ERI": {"name": "Eritrea"},
    "EST": {"name": "Estonia"},
    "ETH": {"name": "Ethiopia"},
    "FLK": {"name": "Falkland Islands (Malvinas)"},
    "FRO": {"name": "Faroe Islands"},
    "FJI": {"name": "Fiji"},
    "FIN": {"name": "Finland"},
    "FRA": {"name": "France, Metropolitan"},
    "GUF": {"name": "French Guiana"},
    "PYF": {"name": "French Polynesia"},
    "ATF": {"name": "French Southern Territories"},
    "MKD": {"name": "FYROM"},
    "GAB": {"name": "Gabon"},
    "GMB": {"name": "Gambia"},
    "GEO": {"name": "Georgia"},
    "DEU": {"name": "Germany"},
    "GHA": {"name": "Ghana"},
    "GIB": {"name": "Gibraltar"},
    "GRC": {"name": "Greece"},
    "GRL": {"name": "Greenland"},
    "GRD": {"name": "Grenada"},
    "GLP": {"name": "Guadeloupe"},
    "GUM": {"name": "Guam"},
    "GTM": {"name": "Guatemala"},
    "GGY": {"name": "Guernsey"},
    "GIN": {"name": "Guinea"},
    "GNB": {"name": "Guinea-Bissau"},
    "GUY": {"name": "Guyana"},
    "HTI": {"name": "Haiti"},
    "HMD": {"name": "Heard and Mc Donald Islands"},
    "HND": {"name": "Honduras"},
    "HKG": {"name": "Hong Kong"},
    "HUN": {"name": "Hungary"},
    "ISL": {"name": "Iceland"},
    "IND": {"name": "India"},
    "IDN": {"name": "Indonesia"},
    "IRN": {"name": "Iran (Islamic Republic of)"},
    "IRQ": {"name": "Iraq"},
    "IRL": {"name": "Ireland"},
    "IMN": {"name": "Isle of Man"},
    "ISR": {"name": "Israel"},
    "ITA": {"name": "Italy"},
    "JAM": {"name": "Jamaica"},
    "JPN": {"name": "Japan"},
    "JEY": {"name": "Jersey"},
    "JOR": {"name": "Jordan"},
    "KAZ": {"name": "Kazakhstan"},
    "KEN": {"name": "Kenya"},
    "KIR": {"name": "Kiribati"},
    "KOR": {"name": "Korea, Republic of"},
    "UNK": {"name": "Kosovo, Republic of"},
    "KWT": {"name": "Kuwait"},
    "KGZ": {"name": "Kyrgyzstan"},
    "LAO": {"name": "Lao People's Democratic Republic"},
    "LVA": {"name": "Latvia"},
    "LBN": {"name": "Lebanon"},
    "LSO": {"name": "Lesotho"},
    "LBR": {"name": "Liberia"},
    "LBY": {"name": "Libyan Arab Jamahiriya"},
    "LIE": {"name": "Liechtenstein"},
    "LTU": {"name": "Lithuania"},
    "LUX": {"name": "Luxembourg"},
    "MAC": {"name": "Macau"},
    "MDG": {"name": "Madagascar"},
    "MWI": {"name": "Malawi"},
    "MYS": {"name": "Malaysia"},
    "MDV": {"name": "Maldives"},
    "MLI": {"name": "Mali"},
    "MLT": {"name": "Malta"},
    "MHL": {"name": "Marshall Islands"},
    "MTQ": {"name": "Martinique"},
    "MRT": {"name": "Mauritania"},
    "MUS": {"name": "Mauritius"},
    "MYT": {"name": "Mayotte"},
    "MEX": {"name": "Mexico"},
    "FSM": {"name": "Micronesia, Federated States of"},
    "MDA": {"name": "Moldova, Republic of"},
    "MCO": {"name": "Monaco"},
    "MNG": {"name": "Mongolia"},
    "MNE": {"name": "Montenegro"},
    "MSR": {"name": "Montserrat"},
    "MAR": {"name": "Morocco"},
    "MOZ": {"name": "Mozambique"},
    "MMR": {"name": "Myanmar"},
    "NAM": {"name": "Namibia"},
    "NRU": {"name": "Nauru"},
    "NPL": {"name": "Nepal"},
    "NLD": {"name": "Netherlands"},
    "ANT": {"name": "Netherlands Antilles"},
    "NCL": {"name": "New Caledonia"},
    "NZL": {"name": "New Zealand"},
    "NIC": {"name": "Nicaragua"},
    "NER": {"name": "Niger"},
    "NGA": {"name": "Nigeria"},
    "NIU": {"name": "Niue"},
    "NFK": {"name": "Norfolk Island"},
    "PRK": {"name": "North Korea"},
    "MNP": {"name": "Northern Mariana Islands"},
    "NOR": {"name": "Norway"},
    "OMN": {"name": "Oman"},
    "PAK": {"name": "Pakistan"},
    "PLW": {"name": "Palau"},
    "PSE": {"name": "Palestinian Territory, Occupied"},
    "PAN": {"name": "Panama"},
    "PNG": {"name": "Papua New Guinea"},
    "PRY": {"name": "Paraguay"},
    "PER": {"name": "Peru"},
    "PHL": {"name": "Philippines"},
    "PCN": {"name": "Pitcairn"},
    "POL": {"name": "Poland"},
    "PRT": {"name": "Portugal"},
    "PRI": {"name": "Puerto Rico"},
    "QAT": {"name": "Qatar"},
    "REU": {"name": "Reunion"},
    "ROM": {"name": "Romania"},
    "RUS": {"name": "Russian Federation"},
    "RWA": {"name": "Rwanda"},
    "KNA": {"name": "Saint Kitts and Nevis"},
    "LCA": {"name": "Saint Lucia"},
    "VCT": {"name": "Saint Vincent and the Grenadines"},
    "WSM": {"name": "Samoa"},
    "SMR": {"name": "San Marino"},
    "STP": {"name": "Sao Tome and Principe"},
    "SAU": {"name": "Saudi Arabia"},
    "SEN": {"name": "Senegal"},
    "SRB": {"name": "Serbia"},
    "SYC": {"name": "Seychelles"},
    "SLE": {"name": "Sierra Leone"},
    "SGP": {"name": "Singapore"},
    "SVK": {"name": "Slovak Republic"},
    "SVN": {"name": "Slovenia"},
    "SLB": {"name": "Solomon Islands"},
    "SOM": {"name": "Somalia"},
    "ZAF": {"name": "South Africa"},
    "SGS": {"name": "South Georgia &amp; South Sandwich Islands"},
    "SSD": {"name": "South Sudan"},
    "ESP": {"name": "Spain"},
    "LKA": {"name": "Sri Lanka"},
    "BLM": {"name": "St. Barthelemy"},
    "SHN": {"name": "St. Helena"},
    "MAF": {"name": "St. Martin (French part)"},
    "SPM": {"name": "St. Pierre and Miquelon"},
    "SDN": {"name": "Sudan"},
    "SUR": {"name": "Suriname"},
    "SJM": {"name": "Svalbard and Jan Mayen Islands"},
    "SWZ": {"name": "Swaziland"},
    "SWE": {"name": "Sweden"},
    "CHE": {"name": "Switzerland"},
    "SYR": {"name": "Syrian Arab Republic"},
    "TWN": {"name": "Taiwan"},
    "TJK": {"name": "Tajikistan"},
    "TZA": {"name": "Tanzania, United Republic of"},
    "THA": {"name": "Thailand"},
    "TGO": {"name": "Togo"},
    "TKL": {"name": "Tokelau"},
    "TON": {"name": "Tonga"},
    "TTO": {"name": "Trinidad and Tobago"},
    "SHN": {"name": "Tristan da Cunha"},
    "TUN": {"name": "Tunisia"},
    "TUR": {"name": "Turkey"},
    "TKM": {"name": "Turkmenistan"},
    "TCA": {"name": "Turks and Caicos Islands"},
    "TUV": {"name": "Tuvalu"},
    "UGA": {"name": "Uganda"},
    "UKR": {"name": "Ukraine"},
    "ARE": {"name": "United Arab Emirates"},
    "GBR": {"name": "United Kingdom"},
    "USA": {"name": "United States"},
    "UMI": {"name": "United States Minor Outlying Islands"},
    "URY": {"name": "Uruguay"},
    "UZB": {"name": "Uzbekistan"},
    "VUT": {"name": "Vanuatu"},
    "VAT": {"name": "Vatican City State (Holy See)"},
    "VEN": {"name": "Venezuela"},
    "VNM": {"name": "Viet Nam"},
    "VGB": {"name": "Virgin Islands (British)"},
    "VIR": {"name": "Virgin Islands (U.S.)"},
    "WLF": {"name": "Wallis and Futuna Islands"},
    "ESH": {"name": "Western Sahara"},
    "YEM": {"name": "Yemen"},
    "ZMB": {"name": "Zambia"},
    "ZWE": {"name": "Zimbabwe"}
}

COUNTRY_TO_TERRITORY_MAP = {
    "Canada": {"name": "Canada", "zones": {
        "AB": {"name": "Alberta"},
        "BC": {"name": "British Columbia"},
        "MB": {"name": "Manitoba"},
        "NB": {"name": "New Brunswick"},
        "NL": {"name": "Newfoundland and Labrador"},
        "NT": {"name": "Northwest Territories"},
        "NS": {"name": "Nova Scotia"},
        "NU": {"name": "Nunavut"},
        "ON": {"name": "Ontario"},
        "PE": {"name": "Prince Edward Island"},
        "QC": {"name": "Quebec"},
        "SK": {"name": "Saskatchewan"},
        "YT": {"name": "Yukon Territory"}
    }},
    "Aaland Islands": {"name": "Aaland Islands"},
    "Afghanistan": {"name": "Afghanistan"},
    "Albania": {"name": "Albania"},
    "Algeria": {"name": "Algeria"},
    "American Samoa": {"name": "American Samoa"},
    "Andorra": {"name": "Andorra"},
    "Angola": {"name": "Angola"},
    "Anguilla": {"name": "Anguilla"},
    "Antarctica": {"name": "Antarctica"},
    "Antigua and Barbuda": {"name": "Antigua and Barbuda"},
    "Argentina": {"name": "Argentina"},
    "Armenia": {"name": "Armenia"},
    "Aruba": {"name": "Aruba"},
    "Ascension Island (British)": {"name": "Ascension Island (British)"},
    "Australia": {"name": "Australia"},
    "Austria": {"name": "Austria"},
    "Azerbaijan": {"name": "Azerbaijan"},
    "Bahamas": {"name": "Bahamas"},
    "Bahrain": {"name": "Bahrain"},
    "Bangladesh": {"name": "Bangladesh"},
    "Barbados": {"name": "Barbados"},
    "Belarus": {"name": "Belarus"},
    "Belgium": {"name": "Belgium"},
    "Belize": {"name": "Belize"},
    "Benin": {"name": "Benin"},
    "Bermuda": {"name": "Bermuda"},
    "Bhutan": {"name": "Bhutan"},
    "Bolivia": {"name": "Bolivia"},
    "Bonaire, Sint Eustatius and Saba": {"name": "Bonaire, Sint Eustatius and Saba"},
    "Bosnia and Herzegovina": {"name": "Bosnia and Herzegovina"},
    "Botswana": {"name": "Botswana"},
    "Bouvet Island": {"name": "Bouvet Island"},
    "Brazil": {"name": "Brazil"},
    "British Indian Ocean Territory": {"name": "British Indian Ocean Territory"},
    "Brunei Darussalam": {"name": "Brunei Darussalam"},
    "Bulgaria": {"name": "Bulgaria"},
    "Burkina Faso": {"name": "Burkina Faso"},
    "Burundi": {"name": "Burundi"},
    "Cambodia": {"name": "Cambodia"},
    "Cameroon": {"name": "Cameroon"},
    "Canada": {"name": "Canada"},
    "Canary Islands": {"name": "Canary Islands"},
    "Cape Verde": {"name": "Cape Verde"},
    "Cayman Islands": {"name": "Cayman Islands"},
    "Central African Republic": {"name": "Central African Republic"},
    "Chad": {"name": "Chad"},
    "Chile": {"name": "Chile"},
    "China": {"name": "China"},
    "Christmas Island": {"name": "Christmas Island"},
    "Cocos (Keeling) Islands": {"name": "Cocos (Keeling) Islands"},
    "Colombia": {"name": "Colombia"},
    "Comoros": {"name": "Comoros"},
    "Congo": {"name": "Congo"},
    "Cook Islands": {"name": "Cook Islands"},
    "Costa Rica": {"name": "Costa Rica"},
    "Cote D'Ivoire": {"name": "Cote D'Ivoire"},
    "Croatia": {"name": "Croatia"},
    "Cuba": {"name": "Cuba"},
    "Curacao": {"name": "Curacao"},
    "Cyprus": {"name": "Cyprus"},
    "Czech Republic": {"name": "Czech Republic"},
    "Democratic Republic of Congo": {"name": "Democratic Republic of Congo"},
    "Denmark": {"name": "Denmark"},
    "Djibouti": {"name": "Djibouti"},
    "Dominica": {"name": "Dominica"},
    "Dominican Republic": {"name": "Dominican Republic"},
    "East Timor": {"name": "East Timor"},
    "Ecuador": {"name": "Ecuador"},
    "Egypt": {"name": "Egypt"},
    "El Salvador": {"name": "El Salvador"},
    "Equatorial Guinea": {"name": "Equatorial Guinea"},
    "Eritrea": {"name": "Eritrea"},
    "Estonia": {"name": "Estonia"},
    "Ethiopia": {"name": "Ethiopia"},
    "Falkland Islands (Malvinas)": {"name": "Falkland Islands (Malvinas)"},
    "Faroe Islands": {"name": "Faroe Islands"},
    "Fiji": {"name": "Fiji"},
    "Finland": {"name": "Finland"},
    "France, Metropolitan": {"name": "France, Metropolitan"},
    "French Guiana": {"name": "French Guiana"},
    "French Polynesia": {"name": "French Polynesia"},
    "French Southern Territories": {"name": "French Southern Territories"},
    "FYROM": {"name": "FYROM"},
    "Gabon": {"name": "Gabon"},
    "Gambia": {"name": "Gambia"},
    "Georgia": {"name": "Georgia"},
    "Germany": {"name": "Germany"},
    "Ghana": {"name": "Ghana"},
    "Gibraltar": {"name": "Gibraltar"},
    "Greece": {"name": "Greece"},
    "Greenland": {"name": "Greenland"},
    "Grenada": {"name": "Grenada"},
    "Guadeloupe": {"name": "Guadeloupe"},
    "Guam": {"name": "Guam"},
    "Guatemala": {"name": "Guatemala"},
    "Guernsey": {"name": "Guernsey"},
    "Guinea": {"name": "Guinea"},
    "Guinea-Bissau": {"name": "Guinea-Bissau"},
    "Guyana": {"name": "Guyana"},
    "Haiti": {"name": "Haiti"},
    "Heard and Mc Donald Islands": {"name": "Heard and Mc Donald Islands"},
    "Honduras": {"name": "Honduras"},
    "Hong Kong": {"name": "Hong Kong"},
    "Hungary": {"name": "Hungary"},
    "Iceland": {"name": "Iceland"},
    "India": {"name": "India"},
    "Indonesia": {"name": "Indonesia"},
    "Iran (Islamic Republic of)": {"name": "Iran (Islamic Republic of)"},
    "Iraq": {"name": "Iraq"},
    "Ireland": {"name": "Ireland"},
    "Isle of Man": {"name": "Isle of Man"},
    "Israel": {"name": "Israel"},
    "Italy": {"name": "Italy"},
    "Jamaica": {"name": "Jamaica"},
    "Japan": {"name": "Japan"},
    "Jersey": {"name": "Jersey"},
    "Jordan": {"name": "Jordan"},
    "Kazakhstan": {"name": "Kazakhstan"},
    "Kenya": {"name": "Kenya"},
    "Kiribati": {"name": "Kiribati"},
    "Korea, Republic of": {"name": "Korea, Republic of"},
    "Kosovo, Republic of": {"name": "Kosovo, Republic of"},
    "Kuwait": {"name": "Kuwait"},
    "Kyrgyzstan": {"name": "Kyrgyzstan"},
    "Lao People's Democratic Republic": {"name": "Lao People's Democratic Republic"},
    "Latvia": {"name": "Latvia"},
    "Lebanon": {"name": "Lebanon"},
    "Lesotho": {"name": "Lesotho"},
    "Liberia": {"name": "Liberia"},
    "Libyan Arab Jamahiriya": {"name": "Libyan Arab Jamahiriya"},
    "Liechtenstein": {"name": "Liechtenstein"},
    "Lithuania": {"name": "Lithuania"},
    "Luxembourg": {"name": "Luxembourg"},
    "Macau": {"name": "Macau"},
    "Madagascar": {"name": "Madagascar"},
    "Malawi": {"name": "Malawi"},
    "Malaysia": {"name": "Malaysia"},
    "Maldives": {"name": "Maldives"},
    "Mali": {"name": "Mali"},
    "Malta": {"name": "Malta"},
    "Marshall Islands": {"name": "Marshall Islands"},
    "Martinique": {"name": "Martinique"},
    "Mauritania": {"name": "Mauritania"},
    "Mauritius": {"name": "Mauritius"},
    "Mayotte": {"name": "Mayotte"},
    "Mexico": {"name": "Mexico"},
    "Micronesia, Federated States of": {"name": "Micronesia, Federated States of"},
    "Moldova, Republic of": {"name": "Moldova, Republic of"},
    "Monaco": {"name": "Monaco"},
    "Mongolia": {"name": "Mongolia"},
    "Montenegro": {"name": "Montenegro"},
    "Montserrat": {"name": "Montserrat"},
    "Morocco": {"name": "Morocco"},
    "Mozambique": {"name": "Mozambique"},
    "Myanmar": {"name": "Myanmar"},
    "Namibia": {"name": "Namibia"},
    "Nauru": {"name": "Nauru"},
    "Nepal": {"name": "Nepal"},
    "Netherlands": {"name": "Netherlands"},
    "Netherlands Antilles": {"name": "Netherlands Antilles"},
    "New Caledonia": {"name": "New Caledonia"},
    "New Zealand": {"name": "New Zealand"},
    "Nicaragua": {"name": "Nicaragua"},
    "Niger": {"name": "Niger"},
    "Nigeria": {"name": "Nigeria"},
    "Niue": {"name": "Niue"},
    "Norfolk Island": {"name": "Norfolk Island"},
    "North Korea": {"name": "North Korea"},
    "Northern Mariana Islands": {"name": "Northern Mariana Islands"},
    "Norway": {"name": "Norway"},
    "Oman": {"name": "Oman"},
    "Pakistan": {"name": "Pakistan"},
    "Palau": {"name": "Palau"},
    "Palestinian Territory, Occupied": {"name": "Palestinian Territory, Occupied"},
    "Panama": {"name": "Panama"},
    "Papua New Guinea": {"name": "Papua New Guinea"},
    "Paraguay": {"name": "Paraguay"},
    "Peru": {"name": "Peru"},
    "Philippines": {"name": "Philippines"},
    "Pitcairn": {"name": "Pitcairn"},
    "Poland": {"name": "Poland"},
    "Portugal": {"name": "Portugal"},
    "Puerto Rico": {"name": "Puerto Rico"},
    "Qatar": {"name": "Qatar"},
    "Reunion": {"name": "Reunion"},
    "Romania": {"name": "Romania"},
    "Russian Federation": {"name": "Russian Federation"},
    "Rwanda": {"name": "Rwanda"},
    "Saint Kitts and Nevis": {"name": "Saint Kitts and Nevis"},
    "Saint Lucia": {"name": "Saint Lucia"},
    "Saint Vincent and the Grenadines": {"name": "Saint Vincent and the Grenadines"},
    "Samoa": {"name": "Samoa"},
    "San Marino": {"name": "San Marino"},
    "Sao Tome and Principe": {"name": "Sao Tome and Principe"},
    "Saudi Arabia": {"name": "Saudi Arabia"},
    "Senegal": {"name": "Senegal"},
    "Serbia": {"name": "Serbia"},
    "Seychelles": {"name": "Seychelles"},
    "Sierra Leone": {"name": "Sierra Leone"},
    "Singapore": {"name": "Singapore"},
    "Slovak Republic": {"name": "Slovak Republic"},
    "Slovenia": {"name": "Slovenia"},
    "Solomon Islands": {"name": "Solomon Islands"},
    "Somalia": {"name": "Somalia"},
    "South Africa": {"name": "South Africa"},
    "South Georgia &amp; South Sandwich Islands": {"name": "South Georgia &amp; South Sandwich Islands"},
    "South Sudan": {"name": "South Sudan"},
    "Spain": {"name": "Spain"},
    "Sri Lanka": {"name": "Sri Lanka"},
    "St. Barthelemy": {"name": "St. Barthelemy"},
    "St. Helena": {"name": "St. Helena"},
    "St. Martin (French part)": {"name": "St. Martin (French part)"},
    "St. Pierre and Miquelon": {"name": "St. Pierre and Miquelon"},
    "Sudan": {"name": "Sudan"},
    "Suriname": {"name": "Suriname"},
    "Svalbard and Jan Mayen Islands": {"name": "Svalbard and Jan Mayen Islands"},
    "Swaziland": {"name": "Swaziland"},
    "Sweden": {"name": "Sweden"},
    "Switzerland": {"name": "Switzerland"},
    "Syrian Arab Republic": {"name": "Syrian Arab Republic"},
    "Taiwan": {"name": "Taiwan"},
    "Tajikistan": {"name": "Tajikistan"},
    "Tanzania, United Republic of": {"name": "Tanzania, United Republic of"},
    "Thailand": {"name": "Thailand"},
    "Togo": {"name": "Togo"},
    "Tokelau": {"name": "Tokelau"},
    "Tonga": {"name": "Tonga"},
    "Trinidad and Tobago": {"name": "Trinidad and Tobago"},
    "Tristan da Cunha": {"name": "Tristan da Cunha"},
    "Tunisia": {"name": "Tunisia"},
    "Turkey": {"name": "Turkey"},
    "Turkmenistan": {"name": "Turkmenistan"},
    "Turks and Caicos Islands": {"name": "Turks and Caicos Islands"},
    "Tuvalu": {"name": "Tuvalu"},
    "Uganda": {"name": "Uganda"},
    "Ukraine": {"name": "Ukraine"},
    "United Arab Emirates": {"name": "United Arab Emirates"},
    "United Kingdom": {"name": "United Kingdom"},
    "United States": {"name": "United States"},
    "United States Minor Outlying Islands": {"name": "United States Minor Outlying Islands"},
    "Uruguay": {"name": "Uruguay"},
    "Uzbekistan": {"name": "Uzbekistan"},
    "Vanuatu": {"name": "Vanuatu"},
    "Vatican City State (Holy See)": {"name": "Vatican City State (Holy See)"},
    "Venezuela": {"name": "Venezuela"},
    "Viet Nam": {"name": "Viet Nam"},
    "Virgin Islands (British)": {"name": "Virgin Islands (British)"},
    "Virgin Islands (U.S.)": {"name": "Virgin Islands (U.S.)"},
    "Wallis and Futuna Islands": {"name": "Wallis and Futuna Islands"},
    "Western Sahara": {"name": "Western Sahara"},
    "Yemen": {"name": "Yemen"},
    "Zambia": {"name": "Zambia"},
    "Zimbabwe": {"name": "Zimbabwe"},
    "Rest Of The World": {"name": "Rest Of The World"}
}


def get_by_iso_code3(iso_code_3, zone_code=None, default=DEFAULT):
    if zone_code:
        new_default = ISO_CODE3_TO_TERRITORY_MAP.get(iso_code_3, {}).get("name", default)
        return ISO_CODE3_TO_TERRITORY_MAP.get(iso_code_3, {}).get("zones", {}).get(zone_code, {}).get("name", new_default)
    else:
        return ISO_CODE3_TO_TERRITORY_MAP.get(iso_code_3, {}).get("name", default)


def get_by_country(country, zone_code=None, default=DEFAULT):
    if zone_code:
        new_default = COUNTRY_TO_TERRITORY_MAP.get(country, {}).get("name", default)
        return COUNTRY_TO_TERRITORY_MAP.get(country, {}).get("zones", {}).get(zone_code, {}).get("name", new_default)
    else:
        return COUNTRY_TO_TERRITORY_MAP.get(country, {}).get("name", default)
